# config.yaml
host:
  name: "chuk-mcp-runtime"
  log_level: "INFO"

server:
  type: "stdio"
  #auth: "bearer" # this line is needed to enable bearer auth

# optional overrides
sse:
  host: "0.0.0.0"
  port: 8000
  sse_path: "/sse"
  message_path: "/messages/"
  log_level: "info"
  access_log: true

proxy:
  enabled: false
  namespace: "proxy"
  openai_compatible: false   # ← set to true if you want underscores

# mcp_servers:
#   time:
#     type: "stdio"
#     command: "uvx"
#     args: ["mcp-server-time", "--local-timezone", "America/New_York"]
#   echo:
#     enabled: true
#     location: "../mcp-echo-server/src"
#     tools:
#       enabled: true
#       module: "mcp_echo_server.echo_tools.tools"

# Session Management Tools
session_tools:
  enabled: false  # Master switch for all session tools
  
  tools:
    # Core session operations
    get_current_session:
      enabled: true
      description: "Get information about the current session context"
    
    set_session:
      enabled: true
      description: "Set the session context for subsequent operations"
    
    clear_session:
      enabled: true
      description: "Clear the current session context"
    
    # Session management operations
    list_sessions:
      enabled: true
      description: "List all active sessions"
    
    get_session_info:
      enabled: true
      description: "Get detailed information about a specific session"
    
    create_session:
      enabled: true
      description: "Create a new session with optional metadata"

# Artifact Management Tools
artifacts:
  enabled: false  # Master switch for all artifact tools
  
  # Storage configuration
  storage_provider: "s3"  # "filesystem", "memory", "s3", "ibm_cos"
  session_provider: "redis"      # "memory", "redis"
  bucket: "chuk-sandbox-2"
  
  # Tool configuration - fine-grained control over which tools are available
  tools:
    # Core file operations (typically always enabled)
    write_file:
      enabled: true
      description: "Create or update text files"
    
    read_file:
      enabled: true
      description: "Read file contents"
    
    list_session_files:
      enabled: true
      description: "List files in current session"
    
    # File management operations
    upload_file:
      enabled: true
      description: "Upload files with base64 content"
    
    delete_file:
      enabled: true  # Set to false to prevent file deletion
      description: "Delete files from storage"
    
    copy_file:
      enabled: true
      description: "Copy files within same session"
    
    move_file:
      enabled: true  # Set to false to prevent file moves
      description: "Move or rename files"
    
    # Directory operations
    list_directory:
      enabled: true
      description: "List contents of directories"
    
    # Metadata and advanced features
    get_file_metadata:
      enabled: true
      description: "Get detailed file information"
    
    get_storage_stats:
      enabled: true  # Set to false to hide storage statistics
      description: "Get storage usage statistics"
    
    # URL generation (often disabled for security)
    get_presigned_url:
      enabled: false  # Disabled by default for security
      description: "Generate temporary download URLs"